name: Publish Release
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/release/')
    steps:
    - name: Validate the release
      uses: actions/github-script@v4
      with:
        script: |
          const ver = "${{ github.ref }}".substring(19)
          const tag = "v" + ver
          try {
            const rel = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: tag
            })
          }
          catch (error) {
            core.setFailed("Could not find a release for version " + ver)
          }
      
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configure repository
      shell: bash
      run: |
        git config user.email "github-actions@hazelcast.com"
        git config user.name "GitHub Actions (Build Release)"

    - name: Finalize the release
      run: |
        ref="${{ github.ref }}"
        branch="${ref:11}" # trim starting 'refs/heads/' (11 chars)
        version="${ref:19}" # trim starting 'refs/heads/release/' (19 chars)
        echo "Tag branch $branch as v$version"
        git tag v$version
        git push --tags
        git push :$branch

    - name: Publish the release
      uses: actions/github-script@v4
      with:
        script: |
          const ver = "${{ github.ref }}".substring(19)
          const tag = "v" + ver
          const rel = await github.repos.getReleaseByTag({
            owner: context.repo.owner,
            repo: context.repo.repo,
            tag: tag
          })
          await github.repos.updateRelease({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: rel.id,
            draft: false
          })